// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW9QrTYgqIUqa8gYfFOLWOLVTw62QPHXg',
    appId: '1:996644020407:web:747c34683919daeb0a6d32',
    messagingSenderId: '996644020407',
    projectId: 'firestoredb-chatapp',
    authDomain: 'firestoredb-chatapp.firebaseapp.com',
    storageBucket: 'firestoredb-chatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAksuB1v3juSgeXckDj2ExHvEmmJSts-zY',
    appId: '1:996644020407:android:cea507fb5437cde90a6d32',
    messagingSenderId: '996644020407',
    projectId: 'firestoredb-chatapp',
    storageBucket: 'firestoredb-chatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp20jaoZ4wzRJDBZHqZpdciAx596ALoMs',
    appId: '1:996644020407:ios:407836318941fd250a6d32',
    messagingSenderId: '996644020407',
    projectId: 'firestoredb-chatapp',
    storageBucket: 'firestoredb-chatapp.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
